version: '3'

services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
        ports:
            - "8080:8080"
        env_file:
            -   ./.env
